config/routes.rb
Rails.application.routes.draw do

  resources :result_tnmtseconds do
    collection do
      get :init
    end
  end

  resources :tournament_seconds do
    collection do 
      get :init
      get :init_semifinal
      get :init_final
      post :bet
      get :show_everyones
    end
  end

  resources :result_tnmtfirsts do
    collection do
      get :init
    end
  end

  resources :bet_winners do
    collection do
      get :init
      post :bet
      get :show_everyones
    end
  end

  resources :tournament_firsts do
    collection do 
      get :init
      post :bet
      get :show_everyones
    end
  end

  resources :result_seconds do
    collection do
      get :init
    end
  end

  root :to => 'welcome#index'
  resources :welcome, :only => ['index']
  get :portals, :to => 'portals#index', :as => :user_root

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  resources :user_infos do
    collection do
      post :commit_voice
      get :init
    end
  end

  resources :portals

  resources :dashboard do
    collection do
      get :load_graph
    end
  end

  resources :news_feeds do
    collection do
      get :show_pickups
    end
  end

  resources :bet_firsts do
    collection do
      get :init
      get :show_everyones
      get :get_score
      get :show_ranking
      post :bet
    end
  end

  resources :bet_seconds do
    collection do
      get :init
      post :bet
      get :show_everyones
    end
  end

  resources :result_firsts do
    collection do
      get :init
    end
  end

  resources :countries do
    collection do
      get :init
    end
  end

end

app/models/result_tnmtsecond.rb
class ResultTnmtsecond < ActiveRecord::Base
  def self.init
    matches = Array.new
    matches << "7/4 1:00,FRA-DEU"
    matches << "7/5 1:00,ARG-BEL"
    matches << "7/5 5:00,BRA-COL"
    matches << "7/6 5:00,NLD-CRI"

    ResultTnmtsecond.destroy_all
    matches.each do |m|
      info = m.split(",")
      rtf = ResultTnmtsecond.new
      rtf.match_code = info[1]
      rtf.score_l = ""
      rtf.score_r = ""
      rtf.save
    end
  end
end

app/controllers/result_tnmtseconds_controller.rb
class ResultTnmtsecondsController < ApplicationController
  before_action :set_result_tnmtsecond, only: [:show, :edit, :update, :destroy]

  def init
    ResultTnmtsecond.init
    redirect_to user_root_path
  end

  # GET /result_tnmtseconds
  # GET /result_tnmtseconds.json
  def index
    @result_tnmtseconds = ResultTnmtsecond.all
  end

  # GET /result_tnmtseconds/1
  # GET /result_tnmtseconds/1.json
  def show
  end

  # GET /result_tnmtseconds/new
  def new
    @result_tnmtsecond = ResultTnmtsecond.new
  end

  # GET /result_tnmtseconds/1/edit
  def edit
  end

  # POST /result_tnmtseconds
  # POST /result_tnmtseconds.json
  def create
    @result_tnmtsecond = ResultTnmtsecond.new(result_tnmtsecond_params)

    respond_to do |format|
      if @result_tnmtsecond.save
        format.html { redirect_to @result_tnmtsecond, notice: 'Result tnmtsecond was successfully created.' }
        format.json { render :show, status: :created, location: @result_tnmtsecond }
      else
        format.html { render :new }
        format.json { render json: @result_tnmtsecond.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /result_tnmtseconds/1
  # PATCH/PUT /result_tnmtseconds/1.json
  def update
    respond_to do |format|
      if @result_tnmtsecond.update(result_tnmtsecond_params)
        format.html { redirect_to @result_tnmtsecond, notice: 'Result tnmtsecond was successfully updated.' }
        format.json { render :show, status: :ok, location: @result_tnmtsecond }
      else
        format.html { render :edit }
        format.json { render json: @result_tnmtsecond.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /result_tnmtseconds/1
  # DELETE /result_tnmtseconds/1.json
  def destroy
    @result_tnmtsecond.destroy
    respond_to do |format|
      format.html { redirect_to result_tnmtseconds_url, notice: 'Result tnmtsecond was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_result_tnmtsecond
      @result_tnmtsecond = ResultTnmtsecond.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def result_tnmtsecond_params
      params.require(:result_tnmtsecond).permit(:match_code, :score_l, :score_r)
    end
end

app/helpers/result_tnmtseconds_helper.rb
module ResultTnmtsecondsHelper
end

app/views/result_tnmtseconds/_form.html.erb
<%= form_for(@result_tnmtsecond) do |f| %>
  <% if @result_tnmtsecond.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@result_tnmtsecond.errors.count, "error") %> prohibited this result_tnmtsecond from being saved:</h2>

      <ul>
      <% @result_tnmtsecond.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :match_code %><br>
    <%= f.text_field :match_code %>
  </div>
  <div class="field">
    <%= f.label :score_l %><br>
    <%= f.text_field :score_l %>
  </div>
  <div class="field">
    <%= f.label :score_r %><br>
    <%= f.text_field :score_r %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/result_tnmtseconds/edit.html.erb
<h1>Editing result_tnmtsecond</h1>

<%= render 'form' %>

<%= link_to 'Show', @result_tnmtsecond %> |
<%= link_to 'Back', result_tnmtseconds_path %>

app/views/result_tnmtseconds/index.html.erb
<h1>Listing result_tnmtseconds</h1>

<table>
  <thead>
    <tr>
      <th>Match code</th>
      <th>Score l</th>
      <th>Score r</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @result_tnmtseconds.each do |result_tnmtsecond| %>
      <tr>
        <td><%= result_tnmtsecond.match_code %></td>
        <td><%= result_tnmtsecond.score_l %></td>
        <td><%= result_tnmtsecond.score_r %></td>
        <td><%= link_to 'Show', result_tnmtsecond %></td>
        <td><%= link_to 'Edit', edit_result_tnmtsecond_path(result_tnmtsecond) %></td>
        <td><%= link_to 'Destroy', result_tnmtsecond, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Result tnmtsecond', new_result_tnmtsecond_path %>

app/views/result_tnmtseconds/new.html.erb
<h1>New result_tnmtsecond</h1>

<%= render 'form' %>

<%= link_to 'Back', result_tnmtseconds_path %>

app/views/result_tnmtseconds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Match code:</strong>
  <%= @result_tnmtsecond.match_code %>
</p>

<p>
  <strong>Score l:</strong>
  <%= @result_tnmtsecond.score_l %>
</p>

<p>
  <strong>Score r:</strong>
  <%= @result_tnmtsecond.score_r %>
</p>

<%= link_to 'Edit', edit_result_tnmtsecond_path(@result_tnmtsecond) %> |
<%= link_to 'Back', result_tnmtseconds_path %>