config/routes.rb
Rails.application.routes.draw do

  resources :result_tnmtseconds do
    collection do
      get :init
    end
  end

  resources :tournament_seconds do
    collection do 
      get :init
      get :init_semifinal
      get :init_final
      post :bet
      get :show_everyones
    end
  end

  resources :result_tnmtfirsts do
    collection do
      get :init
    end
  end

  resources :bet_winners do
    collection do
      get :init
      post :bet
      get :show_everyones
    end
  end

  resources :tournament_firsts do
    collection do 
      get :init
      post :bet
      get :show_everyones
    end
  end

  resources :result_seconds do
    collection do
      get :init
    end
  end

  root :to => 'welcome#index'
  resources :welcome, :only => ['index']
  get :portals, :to => 'portals#index', :as => :user_root

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  resources :user_infos do
    collection do
      post :commit_voice
      get :init
    end
  end

  resources :portals

  resources :dashboard do
    collection do
      get :load_graph
    end
  end

  resources :news_feeds do
    collection do
      get :show_pickups
    end
  end

  resources :bet_firsts do
    collection do
      get :init
      get :show_everyones
      get :get_score
      get :show_ranking
      post :bet
    end
  end

  resources :bet_seconds do
    collection do
      get :init
      post :bet
      get :show_everyones
    end
  end

  resources :result_firsts do
    collection do
      get :init
    end
  end

  resources :countries do
    collection do
      get :init
    end
  end

end

app/models/portal.rb
class Portal < ActiveRecord::Base
end

app/controllers/portals_controller.rb
class PortalsController < ApplicationController
  before_action :set_porjal, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /portals
  # GET /portals.json
  def index
    @portals = Portal.all
    @users = User.all.order("id")
    @news_feeds = NewsFeed.order("id DESC").limit(12)

    @score_list = Array.new
    temp_list = Array.new
    users = User.all
    users.each do |u|
      #score = BetFirst.get_score u.id
      #score_2 = BetSecond.get_score u.id
      #score_t16 = TournamentFirst.get_score u.id
      #score = score + score_2 + score_t16
      score_1 = BetFirst.get_score u.id
      score_2 = BetSecond.get_score u.id
      score_t16 = TournamentFirst.get_score u.id
      score_t8 = TournamentSecond.get_score u.id
      score = score_1 + score_2 + score_t16 + score_t8
      score_info = Array.new
      score_info << u.user_info.name
      score_info << score.to_i
      temp_list << score_info
    end
    @score_list = temp_list.sort{|a,b|
      b[1] <=> a[1]
    }
  end

  # GET /portals/1
  # GET /portals/1.json
  def show
  end

  # GET /portals/new
  def new
    @portal = Portal.new
  end

  # GET /portals/1/edit
  def edit
  end

  # POST /portals
  # POST /portals.json
  def create
    @portal = Portal.new(portal_params)

    respond_to do |format|
      if @portal.save
        format.html { redirect_to @portal, notice: 'Portal was successfully created.' }
        format.json { render :show, status: :created, location: @portal }
      else
        format.html { render :new }
        format.json { render json: @portal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portals/1
  # PATCH/PUT /portals/1.json
  def update
    respond_to do |format|
      if @portal.update(portal_params)
        format.html { redirect_to @portal, notice: 'Portal was successfully updated.' }
        format.json { render :show, status: :ok, location: @portal }
      else
        format.html { render :edit }
        format.json { render json: @portal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portals/1
  # DELETE /portals/1.json
  def destroy
    @portal.destroy
    respond_to do |format|
      format.html { redirect_to portals_url, notice: 'Portal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portal
      @portal = Portal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def portal_params
      params[:portal]
    end
end

app/helpers/portals_helper.rb
module PortalsHelper
end

app/views/portals/_form.html.erb
<%= form_for(@portal) do |f| %>
  <% if @portal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@portal.errors.count, "error") %> prohibited this portal from being saved:</h2>

      <ul>
      <% @portal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/portals/edit.html.erb
<h1>Editing portal</h1>

<%= render 'form' %>

<%= link_to 'Show', @portal %> |
<%= link_to 'Back', portals_path %>

app/views/portals/index.html.erb
<div class="col-xs-12">
<%
=begin
%>
<%
=end
%>
  <br/>
  <ul id="ticker01" style="width:100%;">
    <% prev = "" %>
    <% rank = 1 %>
    <% @score_list.each do |s| %>
      <% if prev != "" && s[1].to_s != prev %>
        <% rank = rank + 1 %>
      <% end %>
      <li><span><%=rank%>位 <%=s[0]%> ( <%=s[1]%> pt )　　</span></li>
      <% prev = s[1].to_s %>
    <% end %>
  </ul>

  <h3>ニュースピックアップ</h3><br/>
  <div class="row">
  <% @news_feeds.each_with_index do |nf, i| %>
    <div class="col-sm-3 col-md-2 ms-item">
      <div class="thumbnail">
        <a href="<%=nf.news_url%>" target="_blank">
          <img src="<%=nf.news_img_url%>" style="width:210px">
        </a>
        <div class="caption">
          <p><%=nf.title%></p>
        </div>
      </div>
    </div>
    <% if (i+1)%5 == 0 %>
      </div>
      <div class="row">
    <% end %>
  <% end %>
  </div>
  <% if NewsFeed.all.size > 5 %>
    <a href="<%=show_pickups_news_feeds_path%>">もっと見る</a>
  <% end %>

  <br/>

  <h3>いまの気持ち　
    <a href="<%=edit_user_info_path(current_user.user_info.id)%>">
      <span class="glyphicon glyphicon-edit"></span> 編集
    </a>
  </h3>
  <table class="table table-bordered">
    <thead>
      <th style="width:100px;">名前</th>
      <th style="">いまの気持ち
      </th>
    </thead>
    <tbody>
      <% @users.each do |u| %>
      <tr>
        <td><%= u.user_info.name %></td>
        <td><%= u.user_info.voice %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>



<script type="text/javascript">
<!--
jQuery.fn.liScroll = function(settings) {
  settings = jQuery.extend({
    travelocity: 0.07
  }, settings);        
  return this.each(function(){
    var $strip = jQuery(this);
    $strip.addClass("newsticker")
    var stripWidth = 1;
    $strip.find("li").each(function(i){
      stripWidth += jQuery(this, i).outerWidth(true); // thanks to Michael Haszprunar and Fabien Volpi
    });
    var $mask = $strip.wrap("<div class='mask'></div>");
    var $tickercontainer = $strip.parent().wrap("<div class='tickercontainer'></div>");                                
    var containerWidth = $strip.parent().parent().width();    //a.k.a. 'mask' width     
    $strip.width(stripWidth);            
    var totalTravel = stripWidth+containerWidth;
    var defTiming = totalTravel/settings.travelocity;    // thanks to Scott Waye        
    function scrollnews(spazio, tempo){
      $strip.animate({left: '-='+ spazio}, tempo, "linear", function(){$strip.css("left", containerWidth); scrollnews(totalTravel, defTiming);});
    }
    scrollnews(totalTravel, defTiming);                
    $strip.hover(function(){
      jQuery(this).stop();
    },

    function(){
      var offset = jQuery(this).offset();
      var residualSpace = offset.left + stripWidth;
      var residualTime = residualSpace/settings.travelocity;
      scrollnews(residualSpace, residualTime);
    });            
  });    
};

$(function(){
    $("ul#ticker01").liScroll({travelocity: 0.07});
});
// -->
</script>

app/views/portals/new.html.erb
<h1>New portal</h1>

<%= render 'form' %>

<%= link_to 'Back', portals_path %>

app/views/portals/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_portal_path(@portal) %> |
<%= link_to 'Back', portals_path %>