config/routes.rb
Rails.application.routes.draw do

  resources :result_tnmtseconds do
    collection do
      get :init
    end
  end

  resources :tournament_seconds do
    collection do 
      get :init
      get :init_semifinal
      get :init_final
      post :bet
      get :show_everyones
    end
  end

  resources :result_tnmtfirsts do
    collection do
      get :init
    end
  end

  resources :bet_winners do
    collection do
      get :init
      post :bet
      get :show_everyones
    end
  end

  resources :tournament_firsts do
    collection do 
      get :init
      post :bet
      get :show_everyones
    end
  end

  resources :result_seconds do
    collection do
      get :init
    end
  end

  root :to => 'welcome#index'
  resources :welcome, :only => ['index']
  get :portals, :to => 'portals#index', :as => :user_root

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  resources :user_infos do
    collection do
      post :commit_voice
      get :init
    end
  end

  resources :portals

  resources :dashboard do
    collection do
      get :load_graph
    end
  end

  resources :news_feeds do
    collection do
      get :show_pickups
    end
  end

  resources :bet_firsts do
    collection do
      get :init
      get :show_everyones
      get :get_score
      get :show_ranking
      post :bet
    end
  end

  resources :bet_seconds do
    collection do
      get :init
      post :bet
      get :show_everyones
    end
  end

  resources :result_firsts do
    collection do
      get :init
    end
  end

  resources :countries do
    collection do
      get :init
    end
  end

end

app/models/result_tnmtfirst.rb
class ResultTnmtfirst < ActiveRecord::Base

  def self.init
    matches = Array.new
    matches << "6/29 1:00,BRA-CHL"
    matches << "6/29 5:00,COL-URY"
    matches << "6/30 1:00,NLD-MEX"
    matches << "6/30 5:00,CRI-GRC"
    matches << "7/1 1:00,FRA-NGA"
    matches << "7/1 5:00,DEU-DZA"
    matches << "7/2 1:00,ARG-CHE"
    matches << "7/2 5:00,BEL-USA"

    ResultTnmtfirst.destroy_all
    matches.each do |m|
      info = m.split(",")
      rtf = ResultTnmtfirst.new
      rtf.match_code = info[1]
      rtf.score_l = ""
      rtf.score_r = ""
      rtf.save
    end
  end
end

app/controllers/result_tnmtfirsts_controller.rb
class ResultTnmtfirstsController < ApplicationController
  before_action :set_result_tnmtfirst, only: [:show, :edit, :update, :destroy]

  def init
    #ResultTnmtfirst.init
    redirect_to user_root_path
  end

  # GET /result_tnmtfirsts
  # GET /result_tnmtfirsts.json
  def index
    @result_tnmtfirsts = ResultTnmtfirst.all
  end

  # GET /result_tnmtfirsts/1
  # GET /result_tnmtfirsts/1.json
  def show
  end

  # GET /result_tnmtfirsts/new
  def new
    @result_tnmtfirst = ResultTnmtfirst.new
  end

  # GET /result_tnmtfirsts/1/edit
  def edit
  end

  # POST /result_tnmtfirsts
  # POST /result_tnmtfirsts.json
  def create
    @result_tnmtfirst = ResultTnmtfirst.new(result_tnmtfirst_params)

    respond_to do |format|
      if @result_tnmtfirst.save
        format.html { redirect_to @result_tnmtfirst, notice: 'Result tnmtfirst was successfully created.' }
        format.json { render :show, status: :created, location: @result_tnmtfirst }
      else
        format.html { render :new }
        format.json { render json: @result_tnmtfirst.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /result_tnmtfirsts/1
  # PATCH/PUT /result_tnmtfirsts/1.json
  def update
    respond_to do |format|
      if @result_tnmtfirst.update(result_tnmtfirst_params)
        format.html { redirect_to @result_tnmtfirst, notice: 'Result tnmtfirst was successfully updated.' }
        format.json { render :show, status: :ok, location: @result_tnmtfirst }
      else
        format.html { render :edit }
        format.json { render json: @result_tnmtfirst.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /result_tnmtfirsts/1
  # DELETE /result_tnmtfirsts/1.json
  def destroy
    @result_tnmtfirst.destroy
    respond_to do |format|
      format.html { redirect_to result_tnmtfirsts_url, notice: 'Result tnmtfirst was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_result_tnmtfirst
      @result_tnmtfirst = ResultTnmtfirst.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def result_tnmtfirst_params
      params.require(:result_tnmtfirst).permit(:match_code, :score_l, :score_r)
    end
end

app/helpers/result_tnmtfirsts_helper.rb
module ResultTnmtfirstsHelper
end

app/views/result_tnmtfirsts/_form.html.erb
<%= form_for(@result_tnmtfirst) do |f| %>
  <% if @result_tnmtfirst.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@result_tnmtfirst.errors.count, "error") %> prohibited this result_tnmtfirst from being saved:</h2>

      <ul>
      <% @result_tnmtfirst.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :match_code %><br>
    <%= f.text_field :match_code %>
  </div>
  <div class="field">
    <%= f.label :score_l %><br>
    <%= f.text_field :score_l %>
  </div>
  <div class="field">
    <%= f.label :score_r %><br>
    <%= f.text_field :score_r %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/result_tnmtfirsts/edit.html.erb
<h1>Editing result_tnmtfirst</h1>

<%= render 'form' %>

<%= link_to 'Show', @result_tnmtfirst %> |
<%= link_to 'Back', result_tnmtfirsts_path %>

app/views/result_tnmtfirsts/index.html.erb
<h1>Listing result_tnmtfirsts</h1>

<table>
  <thead>
    <tr>
      <th>Match code</th>
      <th>Score l</th>
      <th>Score r</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @result_tnmtfirsts.each do |result_tnmtfirst| %>
      <tr>
        <td><%= result_tnmtfirst.match_code %></td>
        <td><%= result_tnmtfirst.score_l %></td>
        <td><%= result_tnmtfirst.score_r %></td>
        <td><%= link_to 'Show', result_tnmtfirst %></td>
        <td><%= link_to 'Edit', edit_result_tnmtfirst_path(result_tnmtfirst) %></td>
        <td><%= link_to 'Destroy', result_tnmtfirst, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Result tnmtfirst', new_result_tnmtfirst_path %>

app/views/result_tnmtfirsts/new.html.erb
<h1>New result_tnmtfirst</h1>

<%= render 'form' %>

<%= link_to 'Back', result_tnmtfirsts_path %>

app/views/result_tnmtfirsts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Match code:</strong>
  <%= @result_tnmtfirst.match_code %>
</p>

<p>
  <strong>Score l:</strong>
  <%= @result_tnmtfirst.score_l %>
</p>

<p>
  <strong>Score r:</strong>
  <%= @result_tnmtfirst.score_r %>
</p>

<%= link_to 'Edit', edit_result_tnmtfirst_path(@result_tnmtfirst) %> |
<%= link_to 'Back', result_tnmtfirsts_path %>