config/routes.rb
Rails.application.routes.draw do

  resources :result_tnmtseconds do
    collection do
      get :init
    end
  end

  resources :tournament_seconds do
    collection do 
      get :init
      get :init_semifinal
      get :init_final
      post :bet
      get :show_everyones
    end
  end

  resources :result_tnmtfirsts do
    collection do
      get :init
    end
  end

  resources :bet_winners do
    collection do
      get :init
      post :bet
      get :show_everyones
    end
  end

  resources :tournament_firsts do
    collection do 
      get :init
      post :bet
      get :show_everyones
    end
  end

  resources :result_seconds do
    collection do
      get :init
    end
  end

  root :to => 'welcome#index'
  resources :welcome, :only => ['index']
  get :portals, :to => 'portals#index', :as => :user_root

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  resources :user_infos do
    collection do
      post :commit_voice
      get :init
    end
  end

  resources :portals

  resources :dashboard do
    collection do
      get :load_graph
    end
  end

  resources :news_feeds do
    collection do
      get :show_pickups
    end
  end

  resources :bet_firsts do
    collection do
      get :init
      get :show_everyones
      get :get_score
      get :show_ranking
      post :bet
    end
  end

  resources :bet_seconds do
    collection do
      get :init
      post :bet
      get :show_everyones
    end
  end

  resources :result_firsts do
    collection do
      get :init
    end
  end

  resources :countries do
    collection do
      get :init
    end
  end

end

app/models/result_second.rb
class ResultSecond < ActiveRecord::Base
end

app/controllers/result_seconds_controller.rb
class ResultSecondsController < ApplicationController
  before_action :set_result_second, only: [:show, :edit, :update, :destroy]

  def init
=begin
    sets = Array.new
    sets << "a,BRA/MEX"
    sets << "b,NLD/CHL"
    sets << "c,COL/GRC"
    sets << "d,CRI/URY"
    sets << "e,FRA/CHE"
    sets << "f,ARG/NGA"
    sets << "g,DEU/USA"
    sets << "h,BEL/DZA"

    ResultSecond.destroy_all
    sets.each do |s|
      val = s.split(",")
      rs = ResultSecond.new
      rs.group_name = val[0]
      rs.countries = val[1]
      rs.save
    end
=end
    redirect_to result_seconds_path
  end

  # GET /result_seconds
  # GET /result_seconds.json
  def index
    @result_seconds = ResultSecond.all
  end

  # GET /result_seconds/1
  # GET /result_seconds/1.json
  def show
  end

  # GET /result_seconds/new
  def new
    @result_second = ResultSecond.new
  end

  # GET /result_seconds/1/edit
  def edit
  end

  # POST /result_seconds
  # POST /result_seconds.json
  def create
    @result_second = ResultSecond.new(result_second_params)

    respond_to do |format|
      if @result_second.save
        format.html { redirect_to @result_second, notice: 'Result second was successfully created.' }
        format.json { render :show, status: :created, location: @result_second }
      else
        format.html { render :new }
        format.json { render json: @result_second.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /result_seconds/1
  # PATCH/PUT /result_seconds/1.json
  def update
    respond_to do |format|
      if @result_second.update(result_second_params)
        format.html { redirect_to @result_second, notice: 'Result second was successfully updated.' }
        format.json { render :show, status: :ok, location: @result_second }
      else
        format.html { render :edit }
        format.json { render json: @result_second.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /result_seconds/1
  # DELETE /result_seconds/1.json
  def destroy
    @result_second.destroy
    respond_to do |format|
      format.html { redirect_to result_seconds_url, notice: 'Result second was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_result_second
      @result_second = ResultSecond.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def result_second_params
      params.require(:result_second).permit(:group_name, :countries)
    end
end

app/helpers/result_seconds_helper.rb
module ResultSecondsHelper
end

app/views/result_seconds/_form.html.erb
<%= form_for(@result_second) do |f| %>
  <% if @result_second.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@result_second.errors.count, "error") %> prohibited this result_second from being saved:</h2>

      <ul>
      <% @result_second.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :group_name %><br>
    <%= f.text_field :group_name %>
  </div>
  <div class="field">
    <%= f.label :countries %><br>
    <%= f.text_field :countries %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/result_seconds/edit.html.erb
<h1>Editing result_second</h1>

<%= render 'form' %>

<%= link_to 'Show', @result_second %> |
<%= link_to 'Back', result_seconds_path %>

app/views/result_seconds/index.html.erb
<h1>Listing result_seconds</h1>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Group name</th>
      <th>Countries</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @result_seconds.each do |result_second| %>
      <tr>
        <td><%= result_second.group_name %></td>
        <td><%= result_second.countries %></td>
        <td><%= link_to 'Show', result_second %></td>
        <td><%= link_to 'Edit', edit_result_second_path(result_second) %></td>
        <td><%= link_to 'Destroy', result_second, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Result second', new_result_second_path %>

app/views/result_seconds/new.html.erb
<h1>New result_second</h1>

<%= render 'form' %>

<%= link_to 'Back', result_seconds_path %>

app/views/result_seconds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Group name:</strong>
  <%= @result_second.group_name %>
</p>

<p>
  <strong>Countries:</strong>
  <%= @result_second.countries %>
</p>

<%= link_to 'Edit', edit_result_second_path(@result_second) %> |
<%= link_to 'Back', result_seconds_path %>